name: Unit tests

on:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      # Database
      DB_USER: user
      DB_PASSWORD: user
      DB_HOST: 127.0.0.1
      DB_NAME: ttm
      DB_PORT: 3306

      # Upbit (test values)
      UPBIT_ACCESS_KEY: test_access_key
      UPBIT_SECRET_KEY: test_secret_key

      # Discord (test values)
      DISCORD_BOT_TOKEN: test_bot_token
      DISCORD_HISTORY_CHANNEL_ID: 123456789
      DISCORD_ALERT_CHANNEL_ID: 123456789
      DISCORD_LOG_CHANNEL_ID: 123456789
      DISCORD_ADMIN_USER_IDS: 123456789,987654321

      # Trading Scheduler
      ENABLE_TRADING_SCHEDULER: false
      TRADING_INTERVAL_SECONDS: 10

      # Logging
      LOG_LEVEL: INFO
      ENV: Test

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Build and push to local registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: docker/Dockerfile
        tags: localhost:5000/ttm-image:latest

    - name: Set up resources
      run: |
        docker compose -f docker/docker-compose-local.yml up -d

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'

    - name: Set up Poetry 1.6.1
      run: curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run make test
        poetry run coverage json

    - uses: actions/upload-artifact@v4
      with:
        name: test-result
        path: coverage.json
